const fs = require("fs");
const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));
const vm = require("vm");
const crypto = require("crypto").webcrypto;
const context = { crypto, URL };
context.globalThis = context;
vm.createContext(context);
["src/shared/constants.js", "src/shared/generator.js"].forEach((file) => vm.runInContext(fs.readFileSync(file, "utf8"), context));
const { WebPlover } = context;
const assert = (condition, label) => { if (!condition) throw new Error(label); };
assert(!manifest.action.default_popup, "toolbar click does not open a popup");
assert(WebPlover.buildEmail({ department: "qa", mode: "sequential", counter: 1, domain: "webplover.com" }) === "qa-000001@webplover.com", "sequential email");
assert(WebPlover.buildEmail({ department: "dev", mode: "sequential", counter: 12, domain: "webplover.com" }) === "dev-000012@webplover.com", "department email");
assert(WebPlover.buildEmail({ department: "qa", mode: "website", counter: 12, domain: "webplover.com", pageUrl: "https://www.example.com/contact" }) === "example-qa-012@webplover.com", "website email");
assert(WebPlover.normalizeCountry("ca") === "CA", "country normalization");
const profileA = WebPlover.contactProfile({ email: "qa-000001@webplover.com", allocationId: "allocation-1", country: "US" });
const profileB = WebPlover.contactProfile({ email: "qa-000001@webplover.com", allocationId: "allocation-1", country: "US" });
assert(JSON.stringify(profileA) === JSON.stringify(profileB), "deterministic profile");
assert(profileA.email === "qa-000001@webplover.com" && /^[A-Za-z]+ [A-Za-z]+$/.test(profileA.fullName), "safe contact profile");
assert(/^\+1 555-\d{4}$/.test(profileA.phone), "fictional phone format");
assert(WebPlover.contactProfile({ email: "qa-000002@webplover.com", allocationId: "allocation-ca", country: "CA" }).stateRegion === "ON", "Canadian profile");
assert(WebPlover.contactProfile({ email: "qa-000003@webplover.com", allocationId: "allocation-gb", country: "GB" }).country === "GB", "UK profile");
assert(WebPlover.csvCell('a,"b"') === '"a,""b"""', "CSV escaping");
console.log("Generator smoke checks passed.");
